title: Cushyz的狗窝
description: 乱了就是狗窝了 
url: ''
email: 553009599@qq.com

headpic: null

nav:
  - text: 首页
    url: '/'
  - text: 关于
    url:  '/about.html'
  - text: 联系
    url:  '/contact.html'
  - text: 文章列表
    url:  '/archives'

gems: [jekyll-paginate]
paginate: 1
paginate_path: "archives/:num/"

